### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by leshchenko1979** [michalc/aiofastforward#14]
Does `aiofastforward` work with `pytest`?

The test below never finishes:
```python
@pytest.mark.asyncio
async def test_fast_forward():
    with FastForward(get_event_loop()) as fw:
        await sleep(10)
        await fw(9)
```

**Comment by michalc** [comment]
So the tests now all run in Pytest, so I think the answer is yes, it does work with Pytest

But I realise the documentation is unclear in what aiofastforward does - a lot of the functionality only works if the production asyncio code in in a separate task to the test itself.  aiofastforward "only allows pseudo-time to progress by calls to fw", which means that the `await sleep(10)` will wait forever because no pseudo time has passed at this point.

Will close this since it's, well, been years since the issue was posted, but feel free to discuss further. And I'll ponder how to improve the docs...
